GuLidu/urls.py
from django.contrib import admin
from .settings import MEDIA_ROOT
from django.urls import path, include, re_path
from django.views.static import serve
from apps import courses, operations, orgs
import xadmin
from users.views import index

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('orgs.urls', namespace='orgs')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    path('courses/', include('courses.urls', namespace='courses')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('', index, name='index'),
]

apps/courses/urls.py
from django.urls import path, include
from courses.views import *

app_name = 'courses'
urlpatterns = [
    path('courses_list/$', courses_list, name='courses_list'),
    path('courses_detail/<int:course_id>/$', courses_detail, name='courses_detail'),
    path('courses_video/<int:course_id>/$', courses_video, name='courses_video'),
    path('courses_comment/<int:course_id>/$', courses_comment, name='courses_comment'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/operations/urls.py
from django.urls import path, include
from operations.views import *

app_name = 'operations'
urlpatterns = [
    path('user_ask/$', user_ask, name='user_ask'),
    path('user_love/$', user_love, name='user_love'),
    path('user_comment/<int:course_id>/$', user_comment, name='user_comment'),
]

apps/orgs/urls.py
from django.urls import path, include
from orgs.views import *

app_name = 'orgs'
urlpatterns = [
    path('org_list/$', org_list, name='org_list'),
    path('org_detail/<int:org_id>/$', org_detail, name='org_detail'),
    path('org_detail_course/<int:org_id>/$', org_detail_course, name='org_detail_course'),
    path('org_detail_desc/<int:org_id>/$', org_detail_desc, name='org_detail_desc'),
    path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),

    path('teachers_list/$', teachers_list, name='teachers_list'),
    path('teacher_detail/<int:teacher_id>/$', teacher_detail, name='teacher_detail'),
    # path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/courses/models.py
from django.db import models
from orgs.models import OrgInfo, TeacherInfo
from datetime import datetime


# Create your models here.


class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', max_length=200, verbose_name="课程封面")
    name = models.CharField(max_length=20, verbose_name="课程名称")
    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')),
                             max_length=5, verbose_name='课程难度')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    desc = models.CharField(max_length=200, verbose_name='课程简介')
    detail = models.TextField(max_length=200, verbose_name='课程详情')
    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')),
                                max_length=10, verbose_name='课程类别')
    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=100, verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=100, verbose_name='老师教导')
    orginfo = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.DO_NOTHING)
    teacherinfo = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name


class LessonInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="章节名称")
    course = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "章节信息"
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="视频名称")
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default="http://www.atguigu.com", verbose_name='视频链接',
                          max_length=200)
    lessoninfo = models.ForeignKey(LessonInfo, verbose_name="所属章节", on_delete=None, default=1)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "视频信息"
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="资源名称")
    down_load = models.FileField(upload_to='source/', max_length=200,
                                 verbose_name='下载路径')
    cource = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "资源信息"
        verbose_name_plural = verbose_name

apps/orgs/models.py
from django.db import models

# Create your models here.
from datetime import datetime


class CityInfo(models.Model):
    name = models.CharField(max_length=10, verbose_name="城市名称")
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "城市信息"
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name="机构封面")
    name = models.CharField(max_length=20, verbose_name="机构名称")
    course_num = models.IntegerField(default=0, verbose_name='课程数')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    address = models.CharField(max_length=200, verbose_name="机构地址")
    desc = models.CharField(max_length=200, verbose_name='机构简介')
    detail = models.TextField(max_length=200, verbose_name='机构详情')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    category = models.CharField(choices=(('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')),
                                verbose_name='机构类型', max_length=10)
    cityinfo = models.ForeignKey(CityInfo, verbose_name='所在城市', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "机构信息"
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name="讲师头像")
    name = models.CharField(max_length=20, verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3, verbose_name='工作年限')
    work_psoition = models.CharField(max_length=20, verbose_name='工作职位')
    work_style = models.CharField(max_length=20, verbose_name='教学特点')
    work_company = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.DO_NOTHING)
    age = models.IntegerField(default=30, verbose_name='讲师年龄')
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='讲师性别', default='boy')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "讲师信息"
        verbose_name_plural = verbose_name

apps/orgs/views.py
from django.shortcuts import render

from operations.models import UserLove
from .models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

PAGESIZE = 2


def org_list(request):
    all_orgs = OrgInfo.objects.all().order_by('-love_num')
    all_citys = CityInfo.objects.all()
    sort_orgs = all_orgs.order_by('-love_num')[:3]

    pagenum = request.GET.get('page', '')
    cate = request.GET.get('cate', '')
    cityid = request.GET.get('cityid', '')
    sort = request.GET.get('sort', '')
    if cate:
        all_orgs = all_orgs.filter(category=cate)
    if cityid:
        all_orgs = all_orgs.filter(cityinfo_id=int(cityid))
    if sort:
        all_orgs = all_orgs.order_by("-" + sort)

    pa = Paginator(all_orgs, PAGESIZE)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)

    return render(request, 'orgs/org-list.html',
                  {'all_orgs': all_orgs,
                   'all_citys': all_citys,
                   'sort_orgs': sort_orgs,
                   'pages': pages,
                   'cate': cate,
                   'cityid': cityid,
                   'sort': sort})


def org_detail(request, org_id):
    if org_id:
        org = OrgInfo.objects.filter(id=org_id)[0]
        org.love_num += 1
        org.save()
        love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=org_id, love_type='1', love_status=True)
            if love:
                love_status = True
        if org:
            return render(request, "orgs/org-detail-homepage.html",
                          {'org': org, 'detail_type': 'home', 'love_status': love_status})


def org_detail_course(request, org_id):
    if org_id:
        org = OrgInfo.objects.filter(id=org_id)[0]
        all_course = org.courseinfo_set.all()

        love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=org_id, love_type='1', love_status=True)
            if love:
                love_status = True

        pagenum = request.GET.get('page', '')
        pa = Paginator(all_course, 1)
        try:
            pages = pa.page(pagenum)
        except PageNotAnInteger:
            pages = pa.page(1)
        except EmptyPage:
            pages = pa.page(pa.num_pages)
        if org:
            return render(request, "orgs/org-detail-course.html",
                          {'org': org, 'pages': pages, 'detail_type': 'course', 'love_status': love_status})


def org_detail_desc(request, org_id):
    if org_id:
        org = OrgInfo.objects.filter(id=org_id)[0]

        love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=org_id, love_type='1', love_status=True)
            if love:
                love_status = True
        if org:
            return render(request, "orgs/org-detail-desc.html",
                          {'org': org, 'detail_type': 'desc', 'love_status': love_status})


def org_detail_teacher(request, org_id):
    if org_id:
        org = OrgInfo.objects.filter(id=org_id)[0]

        love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=org_id, love_type='1', love_status=True)
            if love:
                love_status = True
        if org:
            return render(request, "orgs/org-detail-teachers.html",
                          {'org': org, 'detail_type': 'teachers', 'love_status': love_status})


def teachers_list(request):
    all_teacher = TeacherInfo.objects.all().order_by('-click_num')
    sort_teacher = all_teacher.order_by('-love_num')[:5]

    pagenum = request.GET.get('page', '')
    sort = request.GET.get('sort', '')
    if sort:
        all_teacher = all_teacher.order_by("-" + sort)

    pa = Paginator(all_teacher, 1)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)
    return render(request, 'orgs/teachers-list.html', {'all_teacher': all_teacher,
                                                       'sort_teacher': sort_teacher,
                                                       'sort': sort,
                                                       'pages': pages
                                                       })


def teacher_detail(request, teacher_id):
    if teacher_id:
        teacher = TeacherInfo.objects.filter(id=teacher_id)[0]
        teacher.click_num += 1
        teacher.save()
        sort_teacher = TeacherInfo.objects.all().order_by('-love_num')[:5]

        teacher_love_status = False
        org_love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=teacher_id, love_type='3', love_status=True)
            if love:
                teacher_love_status = True
            love = UserLove.objects.filter(love_man=request.user, love_id=teacher.work_company.id, love_type='1',
                                           love_status=True)
            if love:
                org_love_status = True
        return render(request, 'orgs/teacher-detail.html', {'teacher': teacher,
                                                            'sort_teacher': sort_teacher,
                                                            'teacher_love_status': teacher_love_status,
                                                            'org_love_status': org_love_status})

templates/orgs/org-detail-base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block mycss1 %}{% endblock %}
{% endblock %}
{% block middle %}
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 " data-favid="22" data-fav-type="1" id="love">
                 {% if love_status %}
                    取消收藏
                  {% else %}
                    收藏
                  {% endif %}


            </div>

        </div>
    </div>
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:courses_list' %}">课程机构</a>></li>
                <li>{% block branch %}{% endblock %}</li>
            </ul>
        </div>
    </section>
    <section>
        <div class="wp list personal_list comp">
            <div class="left">
                <ul>
                    <li {% if detail_type == 'home' %}class="active2" {% endif %}><a
                            href="{% url 'orgs:org_detail' org.id %}">机构首页</a></li>
                    <li {% if detail_type == 'course' %}class="active2" {% endif %}><a
                            href="{% url 'orgs:org_detail_course' org.id %}">机构课程</a></li>
                    <li {% if detail_type == 'desc' %}class="active2" {% endif %}><a
                            href="{% url 'orgs:org_detail_desc' org.id %}">机构介绍</a></li>
                    <li {% if detail_type == 'teachers' %}class="active2" {% endif %}><a
                            href="{% url 'orgs:org_detail_teacher' org.id %}">机构讲师</a></li>
                </ul>
            </div>
            {% block right %}
            {% endblock %}
        </div>

    </section>

{% endblock %}
{% block myjs %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
    <script type="text/javascript">

        $(function () {
            var $precision = $('.precision'),
                score = $precision.attr('data-star-scope'),
                option = {
                    half: true,
                    path: '{% static 'images/' %}',
                    precision: true,
                    size: 24,
                    starOff: 'g_star.png',
                    starOn: 'r_star.png',
                    starHalf: 'h_star.png',
                    hints: ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg: '暂时还未获得评价！',
                    readOnly: true,
                    score: score
                };
            $precision.raty(option);

            $('#love').click(function () {
                {# 如果拿的是非表单类元素的值,用text(),如果是表单类元素用val() #}
                var love_id = {{ org.id }};
                var love_type = '1';
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_love' %}',
                    data: {
                        'love_id': love_id,
                        'love_type': love_type
                    },
                    success: function (callback) {
                        if (callback.status == 'ok') {
                            $('#love').text(callback.msg)
                        } else {
                            alert(callback.msg)
                        }
                    }
                });
                return false;
            })
        })


    </script>
    {% block myjs1 %}
    {% endblock %}
{% endblock %}

templates/orgs/org-detail-homepage.html
{% extends 'orgs/org-detail-base.html' %}
{% load staticfiles %}
{% block title %}机构首页{% endblock %}
{% block branch %}机构首页{% endblock %}
{% block right %}
    <div class="right companycenter layout grouping">
        <div class="head">
            <h1>全部课程</h1>
            <a class="green fr more" href="{% url 'courses:courses_list' %}">查看更多 > </a>
        </div>
        <div class="brief group_list">
            {% for course in org.courseinfo_set.all %}
                <div class="module1_5 box">
                    <a href="{% url 'courses:courses_detail' course.id %}"><img width="214" src="{{ MEDIA_URL }}{{ course.image }}"/></a>
                    <div class="des">
                        <a href="{% url 'courses:courses_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.study_time }}</i></span>
                        <span class="fr">参加人数：{{ course.study_num }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                        <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="{% url 'orgs:teachers_list' %}">查看更多 > </a>
        </div>
        {% for teacher in org.teacherinfo_set.all %}
            <div class="diarys">
                <div class="module5 share company-diary-box" style="padding:10px 0;">
                    <div class="left">
                        <img class="pic" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                        <p>昵称：{{ teacher.name }}</p>
                    </div>
                    <div class="right">
                        <div class="top">
                            <div class="fl">
                                <a href=""><h1>{{ teacher.courseinfo_set.all.0.name }}</h1></a>
                                <span>发表于：{{ teacher.courseinfo_set.all.0.add_time }}</span>
                            </div>
                        </div>
                        <div class="middle" style="border-bottom:0;">{{ teacher.courseinfo_set.all.0.desc }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="{% url 'orgs:org_list' %}">查看更多 > </a>
        </div>
        <div class="cont">
            <p>{{ org.desc }}</p>
        </div>
    </div>
{% endblock %}

templates/orgs/org-detail-teachers.html
{% extends 'orgs/org-detail-base.html' %}
{% load staticfiles %}
{% block title %}机构教师{% endblock %}
{% block branch %}机构教师{% endblock %}
{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">
                {% for teacher in org.teacherinfo_set.all %}
                    <dl class="des users">
                        <dt>
                            <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                <img width="100" height="100" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ teacher.image }}"
                                     src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1>
                                <a href="{% url 'orgs:teacher_detail'  teacher.id %}">
                                    {{ teacher.name }}<span class="key">已认证</span>
                                </a>
                            </h1>
                            <ul class="cont clearfix">
                                <li class="time">工作年限：<span>{{ teacher.work_year }}</span></li>
                                <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/orgs/teacher-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}讲师详情 - 谷粒教育网{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'orgs:teachers_list' %}">授课讲师</a>></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>

    <section>
        <div class="wp butler-detail-box butler-diaryd-box clearfix">
            <div class="fl list">
                <div class="butler_detail_list clearfix">
                    <div class="brief">
                        <dl class="des">
                            <dt>
                                <div class="picpic">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </div>
                                <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                     {% if teacher_love_status %}
                                         取消收藏
                                     {% else %}
                                         收藏
                                     {% endif %}
                                </span>
                                    <span class="fr btn2 shareBtn bdsharebuttonbox">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                                </div>
                            </dt>
                            <dd>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                                </a>
                                <ul class="cont">
                                    <li>工作年限：<span>{{ teacher.work_year }}</span></li>
                                    <li>就职公司：<span>{{ teacher.work_company.name }}</span></li>
                                    <li>工作职位：<span>{{ teacher.work_psoition }}&nbsp;</span></li>
                                    <li>教学特点：<span>{{ teacher.work_style }}</span></li>
                                </ul>
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="butler_detail_cont clearfix">
                    <div class="left layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li class="active"><a href="{% url 'orgs:teacher_detail' teacher.id %}">全部课程</a></li>
                            </ul>
                        </div>
                        <div class="companycenter">
                            <div class="group_list brief">
                                {% for course in teacher.courseinfo_set.all %}
                                    <div class="module1_5 box">
                                        <a href="{% url 'courses:courses_detail' course.id %}">
                                            <img width="214" height="190" class="scrollLoading"
                                                 src="{{ MEDIA_URL }}{{ course.image }}"/>
                                        </a>
                                        <div class="des">
                                            <a href="{% url 'courses:courses_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                            <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                            <span class="fr">学习人数：{{ course.study_num }}</span>
                                        </div>
                                        <div class="bottom">
                                            <span class="fl">{{ course.orginfo.name }}</span>
                                            <span class="star fr  notlogin" data-favid="15">{{ course.love_num }}</span>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="fr list">
                <div class="butler_detail_list">
                    <div class="right butler-company-box">
                        <div class="head">
                            <h1>{{ teacher.work_company.name }}</h1>
                            <p>知名高校，权威教学</p>
                        </div>
                        <div class="pic">
                            <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                                <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.work_company.image }}"/>
                            </a>
                        </div>
                        <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                            <h2 class="center">{{ teacher.work_company.name }}</h2>
                        </a>
                        <p class="center tell">地址：{{ teacher.work_company.address }}</p>
                        <a class="btn" id="jsRightBtn">
                            {% if org_love_status %}
                                取消收藏
                            {% else %}
                                收藏
                            {% endif %}

                        </a>
                    </div>
                </div>
                <div class="butler_detail_cont">
                    <div class="butler_list_box">
                        <div class="right layout">
                            <div class="head">讲师排行榜</div>
                            {% for teacher in sort_teacher %}
                                <dl class="des">
                                    <span class="num fl">{{ forloop.counter }}</span>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        <dt>
                                            <img width="50" height="50" class="scrollLoading"
                                                 src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                        </dt>
                                    </a>
                                    <dd>
                                        <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                            <h1 title="weesmile">{{ teacher.name }}</h1>
                                        </a>
                                        <p>工作年限：<span>{{ teacher.work_year }}</span></p>
                                    </dd>
                                </dl>

                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            $('#jsLeftBtn').click(function () {
                var love_id = {{ teacher.id }};
                var love_type = '3';
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_love' %}',
                    data: {
                        'love_id': love_id,
                        'love_type': love_type
                    },
                    success: function (callback) {
                        if (callback.status == 'ok') {
                            $('#jsLeftBtn').text(callback.msg)
                        } else {
                            alert(callback.msg)
                        }
                    }
                });
                return false


            });

            $('#jsRightBtn').click(function () {
                var love_id = {{ teacher.work_company.id }};
                var love_type = '1';
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_love' %}',
                    data: {
                        'love_id': love_id,
                        'love_type': love_type
                    },
                    success: function (callback) {
                        if (callback.status == 'ok') {
                            $('#jsRightBtn').text(callback.msg)
                        } else {
                            alert(callback.msg)
                        }
                    }
                });
                return false

            });


        })

    </script>
{% endblock %}