GuLidu/urls.py
from django.contrib import admin
from .settings import MEDIA_ROOT
from django.urls import path, include, re_path
from django.views.static import serve
from apps import courses, operations, orgs
import xadmin
from users.views import index

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('orgs.urls', namespace='orgs')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    path('courses/', include('courses.urls', namespace='courses')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('', index, name='index'),
]

apps/courses/urls.py
from django.urls import path, include
from courses.views import *

app_name = 'courses'
urlpatterns = [
    path('courses_list/$', courses_list, name='courses_list'),
    path('courses_detail/<int:course_id>/$', courses_detail, name='courses_detail'),
    path('courses_video/<int:course_id>/$', courses_video, name='courses_video'),
    path('courses_comment/<int:course_id>/$', courses_comment, name='courses_comment'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/orgs/urls.py
from django.urls import path, include
from orgs.views import *

app_name = 'orgs'
urlpatterns = [
    path('org_list/$', org_list, name='org_list'),
    path('org_detail/<int:org_id>/$', org_detail, name='org_detail'),
    path('org_detail_course/<int:org_id>/$', org_detail_course, name='org_detail_course'),
    path('org_detail_desc/<int:org_id>/$', org_detail_desc, name='org_detail_desc'),
    path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),

    path('teachers_list/$', teachers_list, name='teachers_list'),
    path('teacher_detail/<int:teacher_id>/$', teacher_detail, name='teacher_detail'),
    # path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/users/urls.py
from django.urls import path, include
from users.views import *

app_name = 'users'
urlpatterns = [
    path('user_register/$', user_register, name='user_register'),
    path('user_login/$', user_login, name='user_login'),
    path('user_forget/$', user_forget, name='user_forget'),
    path('user_reset/<str:code>', user_reset, name='user_reset'),
    path('user_logout/$', user_logout, name='user_logout'),
    path('user_active/<str:code>', user_active, name='user_active'),
]

# http://127.0.0.1:8000/users/user_reset/MARsUkGo  # 修改密码链接

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block mycss %}{% endblock %}
</head>
<body>
<section class="headerwrap ">
    <header>
        <div class="header2 header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>8888888</b></p></div>
                    <!--登录后跳转-->


                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr"
                                                                    src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ request.user.username }}</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:user_logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:user_register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:user_login' %}">登录</a>
                    {% endif %}


                </div>

                {% block middle %}
                    <div class="middle">
                        <div class="wp">
                            <a href="/"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
                            <div class="searchbox fr">
                                <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                                    <ul class="selectMenu" id="jsSelectMenu">
                                        <li data-value="course">公开课</li>
                                        <li data-value="org">课程机构</li>
                                        <li data-value="teacher">授课老师</li>
                                    </ul>
                                </div>
                                <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                                <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                            </div>
                        </div>
                    </div>

                    <nav>
                        <div class="nav">
                            <div class="wp">
                                <ul>
                                    <li class="active"><a href="/">首页</a></li>
                                    <li>
                                        <a href="{% url 'courses:courses_list' %}">
                                            公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'orgs:teachers_list' %}">授课教师</a>
                                    </li>
                                    <li><a href="{% url 'orgs:org_list' %}">授课机构</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                    </div>
                {% endblock %}
        </div>
    </header>
</section>
{% block content %} {% endblock %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/logo1.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">88888888</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2012 www.atguigu.com谷粒教育-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2012 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% block myjs %}{% endblock %}
</body>
</html>