GuLidu/urls.py
from django.contrib import admin
from .settings import MEDIA_ROOT
from django.urls import path, include, re_path
from django.views.static import serve
from apps import courses, operations, orgs
import xadmin
from users.views import index

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('orgs.urls', namespace='orgs')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    path('courses/', include('courses.urls', namespace='courses')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('', index, name='index'),
]

apps/courses/urls.py
from django.urls import path, include
from courses.views import *

app_name = 'courses'
urlpatterns = [
    path('courses_list/$', courses_list, name='courses_list'),
    path('courses_detail/<int:course_id>/$', courses_detail, name='courses_detail'),
    path('courses_video/<int:course_id>/$', courses_video, name='courses_video'),
    path('courses_comment/<int:course_id>/$', courses_comment, name='courses_comment'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/operations/urls.py
from django.urls import path, include
from operations.views import *

app_name = 'operations'
urlpatterns = [
    path('user_ask/$', user_ask, name='user_ask'),
    path('user_love/$', user_love, name='user_love'),
    path('user_comment/<int:course_id>/$', user_comment, name='user_comment'),
]

apps/orgs/urls.py
from django.urls import path, include
from orgs.views import *

app_name = 'orgs'
urlpatterns = [
    path('org_list/$', org_list, name='org_list'),
    path('org_detail/<int:org_id>/$', org_detail, name='org_detail'),
    path('org_detail_course/<int:org_id>/$', org_detail_course, name='org_detail_course'),
    path('org_detail_desc/<int:org_id>/$', org_detail_desc, name='org_detail_desc'),
    path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),

    path('teachers_list/$', teachers_list, name='teachers_list'),
    path('teacher_detail/<int:teacher_id>/$', teacher_detail, name='teacher_detail'),
    # path('org_detail_teacher/<int:org_id>/$', org_detail_teacher, name='org_detail_teacher'),
    # path('user_login/$', user_login, name='user_login'),
    # path('user_forget/$', user_forget, name='user_forget'),
    # path('user_reset/<str:code>', user_reset, name='user_reset'),
    # path('user_logout/$', user_logout, name='user_logout'),
    # path('user_active/<str:code>', user_active, name='user_active'),
]

apps/users/urls.py
from django.urls import path, include
from users.views import *

app_name = 'users'
urlpatterns = [
    path('user_register/$', user_register, name='user_register'),
    path('user_login/$', user_login, name='user_login'),
    path('user_forget/$', user_forget, name='user_forget'),
    path('user_reset/<str:code>', user_reset, name='user_reset'),
    path('user_logout/$', user_logout, name='user_logout'),
    path('user_active/<str:code>', user_active, name='user_active'),
]

# http://127.0.0.1:8000/users/user_reset/MARsUkGo  # 修改密码链接

apps/courses/models.py
from django.db import models
from orgs.models import OrgInfo, TeacherInfo
from datetime import datetime


# Create your models here.


class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', max_length=200, verbose_name="课程封面")
    name = models.CharField(max_length=20, verbose_name="课程名称")
    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')),
                             max_length=5, verbose_name='课程难度')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    desc = models.CharField(max_length=200, verbose_name='课程简介')
    detail = models.TextField(max_length=200, verbose_name='课程详情')
    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')),
                                max_length=10, verbose_name='课程类别')
    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=100, verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=100, verbose_name='老师教导')
    orginfo = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.DO_NOTHING)
    teacherinfo = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name


class LessonInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="章节名称")
    course = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "章节信息"
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="视频名称")
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default="http://www.atguigu.com", verbose_name='视频链接',
                          max_length=200)
    lessoninfo = models.ForeignKey(LessonInfo, verbose_name="所属章节", on_delete=None, default=1)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "视频信息"
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="资源名称")
    down_load = models.FileField(upload_to='source/', max_length=200,
                                 verbose_name='下载路径')
    cource = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "资源信息"
        verbose_name_plural = verbose_name

apps/orgs/models.py
from django.db import models

# Create your models here.
from datetime import datetime


class CityInfo(models.Model):
    name = models.CharField(max_length=10, verbose_name="城市名称")
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "城市信息"
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name="机构封面")
    name = models.CharField(max_length=20, verbose_name="机构名称")
    course_num = models.IntegerField(default=0, verbose_name='课程数')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    address = models.CharField(max_length=200, verbose_name="机构地址")
    desc = models.CharField(max_length=200, verbose_name='机构简介')
    detail = models.TextField(max_length=200, verbose_name='机构详情')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    category = models.CharField(choices=(('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')),
                                verbose_name='机构类型', max_length=10)
    cityinfo = models.ForeignKey(CityInfo, verbose_name='所在城市', on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "机构信息"
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name="讲师头像")
    name = models.CharField(max_length=20, verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3, verbose_name='工作年限')
    work_psoition = models.CharField(max_length=20, verbose_name='工作职位')
    work_style = models.CharField(max_length=20, verbose_name='教学特点')
    work_company = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.DO_NOTHING)
    age = models.IntegerField(default=30, verbose_name='讲师年龄')
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='讲师性别', default='boy')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "讲师信息"
        verbose_name_plural = verbose_name

apps/courses/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render

from operations.forms import UserCommentForm
from operations.models import UserLove, UserCourse, UserComment
from .models import *


def courses_list(request):
    all_course = CourseInfo.objects.all().order_by('-add_time')
    sort = request.GET.get('sort', '')
    if sort:
        all_course = all_course.order_by('-' + sort)
    remonment_course = all_course.order_by('-add_time')[:3]

    pagenum = request.GET.get('page', '')
    pa = Paginator(all_course, 1)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)
    return render(request, 'courses/course-list.html', {'all_course': all_course,
                                                        'remonment_course': remonment_course,
                                                        'pages': pages, 'sort': sort})


def courses_detail(request, course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=course_id)[0]
        course.click_num += 1
        course.save()
        relate_course = CourseInfo.objects.filter(category=course.category).exclude(id=course_id)

        course_love_status = False
        if request.user.is_authenticated:
            love = UserLove.objects.filter(love_man=request.user, love_id=course_id, love_type='2', love_status=True)
            if love:
                course_love_status = True

        org_love_status = False
        if request.user.is_authenticated and course:
            love = UserLove.objects.filter(love_man=request.user, love_id=course.orginfo.id, love_type='1',
                                           love_status=True)
            if love:
                org_love_status = True

        return render(request, 'courses/course-detail.html',
                      {'course': course, 'relate_course': relate_course,
                       'course_love_status': course_love_status,
                       'org_love_status': org_love_status})


def courses_video(request, course_id):
    if course_id and request.user.is_authenticated:
        course = CourseInfo.objects.filter(id=course_id)[0]
        usercourse_list = UserCourse.objects.filter(study_man=request.user, study_course=course_id)
        if not usercourse_list:
            usercourse_list = UserCourse.objects.filter(study_man=request.user)
            courses_list = [user_course.study_course for user_course in usercourse_list]
            org_list = [course.orginfo for course in courses_list]
            if course.orginfo not in org_list:
                course.orginfo.study_num += 1
                course.orginfo.save()

            a = UserCourse()
            a.study_man = request.user
            a.study_course = course
            a.save()
            course.study_num += 1
            course.save()

        usercourse_list = UserCourse.objects.filter(study_course=course)
        user_list = [user_course.study_man for user_course in usercourse_list]
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)
        courses_list = list(set([user_course.study_course for user_course in usercourse_list]))

        return render(request, 'courses/course-video.html', {'course': course, 'courses_list': courses_list})
    else:
        return render(request, 'users/login.html')


def courses_comment(request, course_id):
    if course_id and request.user.is_authenticated:
        user_comment_form = UserCommentForm()
        course = CourseInfo.objects.filter(id=course_id)[0]

        usercourse_list = UserCourse.objects.filter(study_course=course)
        user_list = [user_course.study_man for user_course in usercourse_list]
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)
        courses_list = list(set([user_course.study_course for user_course in usercourse_list]))

        comment_list = course.usercomment_set.all()[:10]
        return render(request, 'courses/course-comment.html',
                      {'user_comment_form': user_comment_form, 'course': course, 'courses_list': courses_list,
                       'comment_list': comment_list})

templates/courses/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课评论 - 谷粒教育网{% endblock %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />css/mooc.css
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="/">首页</a>></li>
                    <li><a href="{% url 'courses:courses_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'courses:courses_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>


    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                    <span class="meta-value"><strong>
                        {% if course.level == 'gj' %}
                            高级
                        {% elif course.level == 'zj' %}
                            中级
                        {% else %}
                            初级
                        {% endif %}
                    </strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.study_time }}</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.study_num }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"
                                       href={% url 'courses:courses_video' course.id %}><span>章节</span></a></li>
                                <li><a id="commentOn" class="active"
                                       href="{% url 'courses:courses_comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in comment_list %}
                                    <li class="post-row">
                                        <div class="media">
                                            <span target="_blank"><img
                                                    src='{{ MEDIA_URL }}{{ comment.comment_man.image }}' width='40'
                                                    height='40'/></span>
                                        </div>
                                        <div class="bd">
                                            <div class="tit">
                                                <span target="_blank">{{ comment.comment_man.name }}</span>
                                            </div>
                                            <p class="cnt">{{ comment.comment_content }}</p>
                                            <div class="footer clearfix">
                                                <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>


                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for sourceinfo in course.sourceinfo_set.all %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ sourceinfo.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ sourceinfo.down_load }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacherinfo.image }}' width='80'
                                             height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">{{ course.teacherinfo.name }}</a>
        </span>
                                    <span class="job">{{ course.teacherinfo.work_psoition }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.course_need }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">好好学，啥都有！</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">学过该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in courses_list %}
                                                <li class="curr">
                                                    <a href="{% url 'courses:courses_detail' course.id %}"
                                                       target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ course.image }}">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            $('#js-pl-submit').on('click', function () {
                var comment_course = {{ course.id }};
                var comment_content = $("#js-pl-textarea").val();
                if (comment_content=="") {
                    alert("评论不能为空")
                    return
                }
                $.ajax({
                    {#cache: false,#}
                    type: "POST",
                    url: "{% url 'operations:user_comment' course.id %}",
                    data: {
                        'comment_course': comment_course,
                        'comment_content': comment_content,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    {#async: true,#}
                    success: function (callback) {
                        if (callback.status == 'fail') {
                            if (callback.msg == '用户未登录') {
                                window.location.href = "{% url 'users:user_login' %}";
                            } else {
                                alert(callback.msg)
                            }

                        } else if (callback.status == 'ok') {
                            window.location.reload();//刷新当前页面.
                        }
                    },
                });
            });
            return false

        })

    </script>

{% endblock %}

templates/courses/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频信息 - 谷粒教育网{% endblock %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css'%}" />
     <link rel="stylesheet" type="text/css"href="{% static 'css/guli/course/common-less.css'%}">
{% endblock %}
{% block content %}
        <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:courses_list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:courses_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>


    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>
                        {% if course.level == 'gj' %}
                            高级
                        {% elif course.level == 'zj' %}
                            中级
                        {% else %}
                            初级
                        {% endif %}
                    </strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.study_time }}</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.study_num }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href={% url 'courses:courses_video' course.id %}><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:courses_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.course_notice }}</a> </div>
                </div>

                <div class="mod-chapters">
                {% for lesson in course.lessoninfo_set.all %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.videoinfo_set.all %}
                            <li>
                                <a target="_blank" href='{{ video.url }}' class="J-media-item studyvideo">{{ video.name }} ({{ video.study_time }})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}


                        </ul>
                    </div>
                {% endfor %}


                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for sourceinfo in course.sourceinfo_set.all %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ sourceinfo.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ sourceinfo.down_load }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacherinfo.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">{{ course.teacherinfo.name }}</a>
        </span>
                            <span class="job">{{ course.teacherinfo.work_psoition }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_need }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">好好学，啥都有！</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">学过该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                {% for course in courses_list %}
                                    <li class="curr">
                                        <a href="{% url 'courses:courses_detail' course.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ course.image }}" >
                                            <span class="name autowrap">{{ course.name }}</span>
                                        </a>
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>

                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}