GuLidu/urls.py
from django.contrib import admin
from .settings import MEDIA_ROOT
from django.urls import path, include, re_path
from django.views.static import serve
from apps import courses, operations, orgs
import xadmin
from users.views import index

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('orgs.urls', namespace='orgs')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    path('courses/', include('courses.urls', namespace='courses')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('', index, name='index'),
]

apps/users/urls.py
from django.urls import path, include
from users.views import *

app_name = 'users'
urlpatterns = [
    path('user_register/$', user_register, name='user_register'),
    path('user_login/$', user_login, name='user_login'),
    path('user_forget/$', user_forget, name='user_forget'),
    path('user_reset/<str:code>', user_reset, name='user_reset'),
    path('user_logout/$', user_logout, name='user_logout'),
    path('user_active/<str:code>', user_active, name='user_active'),
]

# http://127.0.0.1:8000/users/user_reset/MARsUkGo  # 修改密码链接

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
from datetime import datetime


class UserProfile(AbstractUser):
    image = models.ImageField(upload_to='user/', max_length=200, verbose_name="用户头像", null=True, blank=True)
    nick_name = models.CharField(max_length=20, verbose_name="用户昵称", null=True, blank=True)
    birthday = models.DateField(verbose_name='用户生日', null=True, blank=True)
    sex = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='用户性别', default='girl')
    address = models.CharField(max_length=200, verbose_name="用户地址", null=True, blank=True)
    phone = models.CharField(max_length=11, verbose_name="用户手机", null=True, blank=True)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)
    is_start = models.BooleanField(default=False, verbose_name="是否激活")

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


class BannerInfo(models.Model):
    image = models.ImageField(upload_to='banner/', max_length=200, verbose_name="轮播图片")
    url = models.URLField(default='http://www.atguigu.com', verbose_name='图片链接', max_length=200)
    is_user = models.BooleanField(default=False, verbose_name='是否为用户登录所用')
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = "轮播图信息"
        verbose_name_plural = verbose_name


class EmailVerifyCode(models.Model):
    code = models.CharField(max_length=20, verbose_name="邮箱验证码")
    email = models.EmailField(verbose_name='验证码邮箱', max_length=200)
    send_type = models.IntegerField(choices=((1, 'register'), (2, 'forget'), (3, 'change')),
                                    verbose_name="验证码类型")
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "邮箱验证码信息"
        verbose_name_plural = verbose_name

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField


class UserRegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=3, max_length=15, error_messages={
        'required': '密码必须填',
        'min_length': '密码最少3位',
        'max_length': '密码最多15位'})
    captcha = CaptchaField()


class UserLoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=3, max_length=15, error_messages={
        'required': '密码必须填',
        'min_length': '密码只是3位',
        'max_length': '密码最多15位'})


class UserForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField()


class UserResetForm(forms.Form):
    password = forms.CharField(required=True, min_length=3, max_length=15, error_messages={
        'required': '密码必须填',
        'min_length': '密码最少3位',
        'max_length': '密码最多15位'})
    password1 = forms.CharField(required=True, min_length=3, max_length=15, error_messages={
        'required': '密码必须填',
        'min_length': '密码最少3位',
        'max_length': '密码最多15位'})

apps/users/views.py
from django.shortcuts import render, redirect, reverse
from .forms import UserRegisterForm, UserLoginForm, UserForgetForm, UserResetForm
from .models import UserProfile, EmailVerifyCode
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from tools.send_mail_tool import send_email_code


def index(request):
    return render(request, 'users/index.html')


def user_login(request):
    if request.method == 'GET':
        return render(request, 'users/login.html')
    else:
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            email = user_login_form.cleaned_data['email']
            password = user_login_form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user:
                if user.is_start:
                    login(request, user)
                    return redirect(reverse('index'))
                else:
                    return render(request, "users/login.html", {'msg': '该账户还未激活,请到邮件激活账户'})

            else:
                return render(request, "users/login.html", {'msg': '邮箱或者密码有误'})

        else:
            return render(request, 'users/login.html',
                          {'user_login_form': user_login_form})


def user_register(request):
    if request.method == 'GET':
        user_register_form = UserRegisterForm()
        return render(request, 'users/register.html',
                      {'user_register_form': user_register_form})
    else:
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            email = user_register_form.cleaned_data['email']
            password = user_register_form.cleaned_data['password']
            user_list = UserProfile.objects.filter(Q(username=email) | Q(email=email))
            if user_list:
                return render(request, "users/register.html", {'msg': '该邮箱已经注册'})
            else:
                a = UserProfile()
                a.username = email
                a.email = email
                a.set_password(password)
                a.save()
                send_email_code(email, 1)  # 1表示注册邮件
                return redirect(reverse('users:user_login'))
        else:
            return render(request, 'users/register.html',
                          {'user_register_form': user_register_form})


def user_logout(request):
    logout(request)
    return redirect(reverse('index'))


def user_active(request, code):
    if code:
        email_ver_list = EmailVerifyCode.objects.filter(code=code)
        if email_ver_list:
            email_ver = email_ver_list[0]
            email = email_ver.email
            user_list = UserProfile.objects.filter(username=email)
            if user_list:
                user = user_list[0]
                user.is_start = True
                user.save()
                return redirect(reverse('users:user_login'))


def user_forget(request):
    if request.method == 'GET':
        user_forget_form = UserForgetForm()
        return render(request, 'users/forgetpwd.html',
                      {'user_forget_form': user_forget_form})
    else:
        user_forget_form = UserForgetForm(request.POST)
        if user_forget_form.is_valid():
            email = user_forget_form.cleaned_data['email']
            user_list = UserProfile.objects.filter(Q(username=email) | Q(email=email))
            if not user_list:
                return render(request, "users/login.html", {'msg': '该用户不存在'})
            else:
                send_email_code(email, 2)  # 2表示修改密码邮件
                return redirect(reverse('users:user_login'))
        else:
            return render(request, 'users/forgetpwd.html',
                          {'user_forget_form': user_forget_form})


def user_reset(request, code):
    if request.method == 'GET':
        user_reset_form = UserResetForm()
        email_list = EmailVerifyCode.objects.filter(code=code)
        if not email_list:
            return render(request, "users/forgetpwd.html", {'msg': '验证码已失效'})
        else:
            return render(request, 'users/password_reset.html',
                          {'user_reset_form': user_reset_form, 'code': code})
    else:
        user_reset_form = UserResetForm(request.POST)
        if user_reset_form.is_valid():
            password = user_reset_form.cleaned_data['password']
            password1 = user_reset_form.cleaned_data['password1']
            if password == password1:
                email_list = EmailVerifyCode.objects.filter(code=code)
                if not email_list:
                    return render(request, "users/forgetpwd.html", {'msg': '验证码已失效'})
                else:
                    email = email_list[0]  # type: EmailVerifyCode
                    user_list = UserProfile.objects.filter(Q(username=email.email) | Q(email=email.email))
                    if user_list:
                        a = user_list[0]
                        a.set_password(password)
                        a.save()
                        return redirect(reverse('users:user_login'))
                    else:
                        return render(request, "users/forgetpwd.html", {'msg': '待修改密码用户已经不存在'})
            else:
                return render(request, 'users/password_reset.html',
                              {'user_reset_form': user_reset_form, 'code': code, 'msg': '两次密码不一致！'})
        else:
            return render(request, 'users/password_reset.html',
                          {'user_reset_form': user_reset_form, 'code': code})

templates/users/forgetpwd.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>谷粒教育首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="{% url 'users:user_login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'users:user_forget' %}">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="/"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="/">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'users:user_forget' %}" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 ">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="None" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ user_forget_form.captcha }}
                    </div>
                    <div class="error btns" id="jsForgetTips">
                        {{ msg }}
                        {% for key,err in user_forget_form.errors.items %}
                            {{ err }}
                        {% endfor %}
                    </div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'users:user_login' %}"> [直接登录]</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>谷粒教育在线网登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li class="active"><a href="{%  url 'users:user_login' %}">[登录]</a></li>
                <li><a href="{%  url 'users:user_register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{%  url 'users:user_login' %}"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="{%  url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="{%  static 'images/mysql.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{%  static 'images/mongoDB.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{%  static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>
                <form action="{% url 'users:user_login' %}" method="post" autocomplete="off">
                    {%  csrf_token %}
                    <div class="form-group marb20 ">
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="email" id="account_l" type="text" placeholder="手机号/邮箱" />
                    </div>
                    <div class="form-group marb8 ">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">
                      {{ msg }}
                            {% for key,err in user_login_form.errors.items %}
                              {{ err }}
                            {% endfor %}
                    </div>
                     <div class="auto-box marb38">

                        <a class="fr" href="{%  url 'users:user_forget' %}">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                </form>
                <p class="form-p">没有谷粒教育在线网帐号？<a href="{%  url 'users:user_register' %}">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/users/password_reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>谷粒教育密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'users:user_reset' code %}" method="post">
            {% csrf_token %}
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="3-15位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password1" id="repwd" placeholder="3-15位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" >
                </li>
            </ul>
            <p>
                {{ msg }}
                {% for key,err in user_reset_form.errors.items %}
                    {{ err }}
                {% endfor %}
            </p>
        </form>
    </div>
</div>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>谷粒教育注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>

<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="{%  url 'users:user_login' %}">[登录]</a></li>
                <li class="active"><a href="{%  url 'users:user_register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{%  url 'users:user_register' %}"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{%  url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2>邮箱注册</h2>
                </div>
                
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'users:user_register' %}" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group marb20 ">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="123@qq.com" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 ">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="123" placeholder="请输入3-15位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 ">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ user_register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {{ msg }}
                            {% for key,err in user_register_form.errors.items %}
                              {{ err }}
                            {% endfor %}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{%  url 'users:user_login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>